In [ ]:
pip install nsedt

Collecting nsedt
  Downloading nsedt-0.0.12-py3-none-any.whl (19 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from nsedt) (2.31.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from nsedt) (1.23.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from nsedt) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nsedt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nsedt) (2023.3.post1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->nsedt) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->nsedt) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->nsedt) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->nsedt) (2023.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->nsedt) (1.16.0)
Installing collected packages: nsedt
Successfully installed nsedt-0.0.12

In [ ]:
from nsedt import equity as eq
from datetime import date, timedelta
import os
import datetime
import pandas as pd

today_date = datetime.date(2023, 10, 13)
tomorrow_date = datetime.date(2023, 11, 24)

In [ ]:
import datetime
from nsedt import equity as eq
from datetime import date, timedelta
import os
import pandas as pd

# Get today's date


# Rest of the code remains the same
symbols= ['CIPLA','INDUSINDBK','TECHM','WIPRO','BHARTIARTL','AXISBANK',
          'HCLTECH','HDFCBANK','HDFCLIFE','RELIANCE','LTIM','TCS','LT','INFY','SBILIFE',
          'HINDALCO','KOTAKBANK','TATASTEEL','UPL','ONGC']

# Create an empty dictionary to store the dataframes

drive_folder = '/content/drive/My Drive/stock_data'

for symbol in symbols:
  file_path = os.path.join(drive_folder, f"{symbol}.csv")
  df=pd.read_csv(file_path)
  data = eq.get_price(today_date, tomorrow_date, symbol=symbol)
  df = df.append(data, ignore_index=True)
  df.to_csv(file_path, index=False)
  print(symbol,"Done")

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

CIPLA Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

INDUSINDBK Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

TECHM Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

WIPRO Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

BHARTIARTL Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

AXISBANK Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

HCLTECH Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

HDFCBANK Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

HDFCLIFE Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

RELIANCE Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

LTIM Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

TCS Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

LT Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

INFY Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

SBILIFE Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

HINDALCO Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

KOTAKBANK Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

TATASTEEL Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

UPL Done

<ipython-input-17-bc00e84ee149>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(data, ignore_index=True)

ONGC Done

In [ ]:
  file_path = os.path.join(drive_folder, f"HDFCBANK.csv")
  df=pd.read_csv(file_path)
  df

,Unnamed: 0.1,Unnamed: 0,Date,Open Price,High Price,Low Price,Close Price,Prev Close Price,Total Traded Quantity,Total Traded Value,...,%K,%D,MACD,Signal Line,MA,RSI Recommendation,Bollinger Recommendation,Stochastic Recommendation,MACD Recommendation,MA Recommendation
0,0.0,0.0,2000-01-03,166.00,170.00,166.00,170.00,157.40,33259,5.638122e+06,...,NaN,NaN,0.000000,0.000000,NaN,Hold,Hold,Hold,Hold,Buy
1,1.0,1.0,2000-01-04,182.00,183.45,171.00,173.80,170.00,168710,2.952261e+07,...,NaN,NaN,0.085256,0.047365,NaN,Hold,Hold,Hold,Sell,Buy
2,2.0,2.0,2000-01-05,170.00,173.90,165.00,166.95,173.80,159820,2.704094e+07,...,NaN,NaN,-0.103785,-0.014582,NaN,Hold,Hold,Hold,Buy,Buy
3,3.0,3.0,2000-01-06,168.00,170.00,165.30,168.30,166.95,85026,1.432166e+07,...,NaN,NaN,-0.138479,-0.056552,NaN,Hold,Hold,Hold,Buy,Buy
4,4.0,4.0,2000-01-07,162.15,171.00,162.15,168.35,168.30,85144,1.420158e+07,...,NaN,NaN,-0.152427,-0.085073,NaN,Hold,Hold,Hold,Buy,Buy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5949,NaN,NaN,2023-11-17 00:00:00,1490.00,1507.50,1489.00,1505.10,1508.35,11850937,1.780584e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5950,NaN,NaN,2023-11-20 00:00:00,1513.00,1513.00,1501.55,1505.20,1505.10,9665726,1.455138e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5951,NaN,NaN,2023-11-21 00:00:00,1519.00,1522.00,1512.10,1517.95,1505.20,12479986,1.894194e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5952,NaN,NaN,2023-11-22 00:00:00,1520.00,1520.00,1503.55,1512.55,1517.95,14561825,2.203560e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5953,NaN,NaN,2023-11-23 00:00:00,1508.50,1523.85,1508.50,1521.30,1512.55,6523110,9.909996e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
'CIPLA', 'INDUSINDBK', 'TECHM', 'WIPRO', 'BHARTIARTL', 'AXISBANK',
           'HCLTECH',




           +++++++++++++++.03

In [ ]:
print(symbol)

HDFCBANK

In [ ]:
df=pd.read_csv("/content/drive/My Drive/stock_data/CIPLA.csv")
df

,Date,Open Price,High Price,Low Price,Close Price,Prev Close Price,Total Traded Quantity,Total Traded Value,52 Week High Price,52 Week Low Price,VWAP,Deliverable Volume,Deliverable Percent,Series
0,2000-01-03,1410.0,1457.35,1380.05,1457.35,1349.40,21060,3.035496e+07,5094.00,836.0,1441.36,-,-,EQ
1,2000-01-04,1537.0,1537.00,1430.00,1465.25,1457.35,30215,4.412698e+07,5094.00,895.0,1460.43,-,-,EQ
2,2000-01-05,1474.0,1474.00,1365.00,1435.05,1465.25,33799,4.826872e+07,5094.00,895.0,1428.11,-,-,EQ
3,2000-01-06,1434.0,1435.00,1349.00,1355.85,1435.05,33083,4.600356e+07,5094.00,895.0,1390.55,-,-,EQ
4,2000-01-07,1370.0,1389.90,1247.40,1247.55,1355.85,66536,8.433351e+07,5094.00,895.0,1267.49,-,-,EQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5878,2023-08-04,1171.0,1238.70,1171.00,1209.75,1165.85,8359856,1.016746e+10,1238.70,852.0,1216.22,3784406,45.27,EQ
5879,2023-08-07 00:00:00,1195.0,1228.50,1174.20,1223.65,1209.75,2468250,2.982997e+09,1238.70,852.0,1208.55,840541,34.05,EQ
5880,2023-08-08 00:00:00,1225.0,1269.00,1224.05,1266.45,1223.65,5064238,6.364738e+09,1269.00,852.0,1256.80,2270463,44.83,EQ
5881,2023-08-09 00:00:00,1270.0,1271.65,1252.25,1266.05,1266.45,2105178,2.659281e+09,1271.65,852.0,1263.21,1220040,57.95,EQ
5882,2023-08-10 00:00:00,1266.0,1277.90,1248.10,1258.95,1266.05,2102129,2.652940e+09,1277.90,852.0,1262.03,1086196,51.67,EQ

In [ ]:
eq.get_price(, tomorrow_date, symbol=symbol)

In [ ]:
from flask import Flask,request,jsonify
import requests

app = Flask(__name__)

@app.route('/',methods=['POST'])
def index():
  return "Hi"
    # data = request.get_json()
   # source_currency = data['queryResult']['parameters']['unit-currency']['currency']
   # amount = data['queryResult']['parameters']['unit-currency']['amount']
    #target_currency = data['queryResult']['parameters']['currency-name']


    #cf = fetch_conversion_factor(source_currency,target_currency)
    #final_amount = amount * cf
    '''final_amount = round(final_amount,2)
    response = {
        'fulfillmentText':"{} {} is {} {}".format(amount,source_currency,final_amount,target_currency)
    }
    return jsonify(response)

def fetch_conversion_factor(source,target):

    url = "https://free.currconv.com/api/v7/convert?q={}_{}&compact=ultra&apiKey=9aa0c54f5ad4c460c36d".format(source,target)

    response = requests.get(url)
    response = response.json()

    return response['{}_{}'.format(source,target)]'''


if __name__ == "__main__":
    app.run(debug=True)